version: '3.9'

services:
        ######################################################################################
        #                     MYSQL for local (Remove if run on VPS)                         #
        ######################################################################################
        tlbbdb:
                image: mysql:5.7
                ports:
                        - "3306:3306"
                volumes:
                        - ./tlbbdb/database:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: "tlbb1234"
                        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                        MYSQL_DATABASE: "tlbbdb"
                restart: always

        ######################################################################################
        #                                  GameServer                                        #
        ######################################################################################
        gs:
                build:
                        context: ./gameserver
                        dockerfile: Dockerfile
                ports:
                        - "7384:7384"
                        - "3731:3731"
                volumes:
                        - ./server:/home/tlbb
                        - ./gameserver/config/odbc.ini:/etc/odbc.ini
                links: # Remove if run on vps
                        - tlbbdb # Remove if run on vps
                environment:
                        - SET_CONTAINER_TIMEZONE=true
                cap_add:
                        - ALL
                privileged: true
                restart: always
        
