version: "3.9"
services:
  mysql:
    image: mysql
    restart: always
    volumes:
       - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: 0.0.0.0
    ports:
      - "3306:3306"
    secrets:
      - mysql_password
      - mysql_root_password
    networks:
      - tlbb-server

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt
volumes:
  mysql_data:
    file: ./data/msql_data
networks:
  tlbb-server:


